name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v4
      # WORKAROUND: https://github.com/actions/setup-node/issues/904
      -
        uses: actions/setup-node@v3
        with:
          node-version: latest
      -
        run: corepack enable
      # END WORKAROUND
      -
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn
      -
        run: yarn install --immutable
      -
        run: yarn build
